Data Wrangling das Bolsas de Doutorado pelo Mundo

Valor das bolsas coletado em 3 de Julho de 2022

André Luzardo, 4 de Julho de 2022

In [1]:
import pandas as pd
from scipy import stats

In [2]:
bolsas = pd.read_csv('BolsasGlassdoor.csv', thousands=',')
big_mac = pd.read_csv('big-mac-source-data.csv')
citations = pd.read_csv('scimagojr country rank 1996-2020.csv')
DollarPPP = pd.read_csv('DollarPPP.csv')

In [3]:
# Use 'bolsas' as main dataframe
# Merge bolsas with selected cols from big_mac
bolsas=pd.merge(bolsas,big_mac.loc[(big_mac['date']=='2022-01-01'),{'local_price','dollar_ex','GDP_dollar','iso_a3'}],left_on='country_code',right_on='iso_a3').rename(columns={'local_price':'bigmac_lcu'})

In [4]:
# Merge bolsas with selected cols from DollarPPP
bolsas=pd.merge(bolsas,DollarPPP.loc[(DollarPPP['TIME']==2021),{'LOCATION','Value'}],left_on='country_code',right_on='LOCATION',how='left').rename(columns={'Value':'ppp'})

In [5]:
# Merge bolsas with selected cols from citations
bolsas=pd.merge(bolsas.replace(to_replace={'Britain':'United Kingdom','New Zeland':'New Zealand'}),citations[{'Country','Citations per document','H index'}].replace(to_replace={'Russian Federation':'Russia'}),left_on='país',right_on='Country',how='left')

In [6]:
# drop repeated cols and set country_code as index
bolsas=bolsas.drop(columns=['iso_a3','LOCATION','país']).set_index('country_code')

In [7]:
bolsas

,bolsa_lcu,dollar_ex,GDP_dollar,bigmac_lcu,ppp,Country,H index,Citations per document
country_code,,,,,,,,
ARG,1158648,105.016500,8571.94,450.00,NaN,Argentina,477,17
AUS,30000,1.419346,52905.40,6.40,1.438979,Australia,1115,23
AUT,27912,0.892061,48592.71,3.80,0.770831,Austria,740,24
BEL,28200,0.892061,44688.46,4.55,0.742723,Belgium,886,26
BRA,32664,5.310000,6822.56,22.90,2.530000,Brazil,649,13
GBR,16815,0.745351,40394.13,3.59,0.692802,United Kingdom,1618,25
CAN,25567,1.271800,43294.80,6.77,1.253066,Canada,1299,26
CHL,9380028,798.600000,12992.98,3100.00,430.349555,Chile,441,17
CHN,43764,6.365350,10511.34,24.40,4.180000,China,1010,10
CZE,299460,21.680200,22942.86,89.00,12.919712,Czech Republic,524,13
DNK,378312,6.637300,61153.92,32.00,6.593618,Denmark,843,30
EGY,84000,15.710000,3600.84,42.50,NaN,Egypt,322,12
EST,21312,0.892061,23035.91,3.40,0.546689,Estonia,317,21
FIN,31776,0.892061,48786.03,4.95,0.829754,Finland,711,26
FRA,21120,0.892061,40298.85,4.35,0.725323,France,1286,23
DEU,25536,0.892061,46215.60,4.46,0.741488,Germany,1429,23
GRC,10908,0.892061,17657.10,3.40,0.547807,Greece,567,19
HKG,216000,7.797550,46657.20,22.00,NaN,Hong Kong,639,24
HUN,2177088,317.511150,15866.22,982.00,154.840118,Hungary,510,18
IND,427260,74.622500,1929.68,190.00,23.300000,India,691,10
IDN,48911844,14382.000000,3921.62,34000.00,4738.640000,Indonesia,259,5
IDN,192000000,14382.000000,3921.62,34000.00,4738.640000,Iran,376,11
IRL,18846,0.892061,85205.50,4.60,0.787487,Ireland,591,23
ISR,99084,3.177750,44181.17,17.00,3.799707,Israel,786,26
ITA,14400,0.892061,31604.43,4.80,0.654354,Italy,1135,21
JPN,1839744,115.225000,40088.60,390.00,100.411640,Japan,1118,18
MYS,24000,4.185500,10231.34,9.99,NaN,Malaysia,373,10
MEX,206208,20.649000,8403.60,69.00,10.043314,Mexico,504,14
MDA,36000,18.000000,4522.60,52.00,NaN,Morocco,222,10
NLD,34704,0.892061,52456.09,4.40,0.769839,Netherlands,1133,30
NZL,27000,1.522649,41164.58,7.00,1.486354,New Zealand,587,23
NOR,516612,8.916050,67326.07,57.00,9.674744,Norway,699,24
PAK,420000,176.520000,1254.86,590.00,NaN,Pakistan,323,10
POL,34008,4.094000,15699.30,14.08,1.837204,Poland,630,12
PRT,13680,0.892061,22148.80,3.45,0.571596,Portugal,560,18
ROU,32400,4.411900,12867.64,10.60,1.745966,Romania,343,9
RUS,816720,77.417500,10115.35,135.00,27.331899,Russia,652,8
SAU,120120,3.751900,19995.70,15.00,NaN,Saudi Arabia,425,14
SGP,30000,1.352150,59794.60,5.90,NaN,Singapore,646,23
SVK,11604,0.892061,19144.92,3.80,0.540124,Slovakia,318,12
SVN,13872,0.892061,25548.77,2.80,0.565944,Slovenia,349,16
ZAF,150883,15.470000,5624.50,39.90,7.040000,South Africa,531,16
KOR,16140672,1205.500000,31638.46,4600.00,847.456839,South Korea,762,15
ESP,19000,0.892061,27179.45,4.58,0.624463,Spain,1010,20
SWE,382056,9.334100,52129.13,54.00,8.708853,Sweden,974,28
CHE,52846,0.931050,87366.60,6.50,1.104516,Switzerland,1085,31
TWN,300000,27.814000,28358.30,75.00,NaN,Taiwan,585,16
THA,240000,33.295000,7187.86,128.00,NaN,Thailand,369,13
TUR,75036,13.415500,8610.03,24.99,2.781851,Turkey,500,12
ARE,120000,3.673050,38661.18,17.00,NaN,United Arab Emirates,241,11
USA,45606,1.000000,63358.49,5.81,1.000000,United States,2577,28

In [8]:
# convert the annual scholarship amount to dollars
bolsas['bolsa_dollar']=bolsas['bolsa_lcu']/bolsas['dollar_ex']
# convert big mac price to dollars
bolsas['bigmac_dollar']=bolsas['bigmac_lcu']/bolsas['dollar_ex']

In [9]:
bolsas.describe()

,bolsa_lcu,dollar_ex,GDP_dollar,bigmac_lcu,ppp,H index,Citations per document,bolsa_dollar,bigmac_dollar
count,5.100000e+01,51.000000,51.000000,51.000000,40.000000,51.000000,51.000000,51.000000,51.000000
mean,5.434967e+06,625.271216,29933.915490,1555.934706,278.730479,720.333333,18.176471,19747.537814,4.033228
std,2.760792e+07,2814.276934,22200.757795,6664.946661,1046.864921,424.903267,6.757828,14352.692440,1.198246
min,1.090800e+04,0.745351,1254.860000,2.800000,0.540124,222.000000,5.000000,2000.000000,1.743792
25%,2.628350e+04,0.892061,10173.345000,4.700000,0.742414,433.000000,12.000000,9030.027404,3.115802
50%,4.560600e+04,4.185500,25548.770000,17.000000,1.616160,630.000000,18.000000,15550.512000,3.997974
75%,3.391560e+05,21.164600,45452.030000,72.000000,9.766887,930.000000,23.500000,28163.432325,4.904375
max,1.920000e+08,14382.000000,87366.600000,34000.000000,4738.640000,2577.000000,31.000000,57941.801583,6.981365

In [10]:
bolsas.to_csv('bolsas.csv')